// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ZaposleniAPI;

#nullable disable

namespace ZaposleniAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260211183752_UpdateZaposleniAndProjekat")]
    partial class UpdateZaposleniAndProjekat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZaposleniAPI.Plata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumIsplate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Iznos")
                        .HasColumnType("numeric");

                    b.Property<string>("ZaposleniJmbg")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Plate");
                });

            modelBuilder.Entity("ZaposleniAPI.Pozicija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DatumDo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DatumOd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NazivPozicije")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ZaposleniJmbg")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Pozicije");
                });

            modelBuilder.Entity("ZaposleniAPI.Projekat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DatumDo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DatumOd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MenadzerJmbg")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Projekti");
                });

            modelBuilder.Entity("ZaposleniAPI.RadioNa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Opis")
                        .HasColumnType("text");

                    b.Property<int>("PozicijaId")
                        .HasColumnType("integer");

                    b.Property<int>("ProjekatId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("RadioNa");
                });

            modelBuilder.Entity("ZaposleniAPI.Zaposleni", b =>
                {
                    b.Property<string>("Jmbg")
                        .HasColumnType("text");

                    b.Property<string>("BrojTelefona")
                        .HasColumnType("text");

                    b.Property<DateTime>("DatumRodjenja")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Jmbg");

                    b.ToTable("Zaposleni");
                });
#pragma warning restore 612, 618
        }
    }
}
